### ISSUE TITLE
RateLimit per API level?

### ISSUE THREAD

**Issue by gembin** [TerminalWitchcraft/actix-ratelimit#4]
Is it possible to control the rate limit at per API level?

For example:
`GET /foo`   100 max requests per minute
`GET /bar`   200 max requests per minute

**Comment by TerminalWitchcraft** [comment]
Yes, it is possible to wrap different instances(You can configure each instance separately according to your needs, like max requests, etc) of this ratelimit middleware to different "scopes" of your app. More information can be found here: https://docs.rs/actix-web/3.0.0-beta.1/actix_web/struct.Scope.html

Hope this helps!

**Comment by TerminalWitchcraft** [comment]
Closing this for now. Feel free to reopen if you have any questions.
