### ISSUE TITLE
a browser request takes 2 requests from x-ratelimit-remaining

### ISSUE THREAD

**Issue by hah** [TerminalWitchcraft/actix-ratelimit#5]
I've set up a web server w/ the minimal example @ https://ratelimit.softwear.sk/
If u check the first request **x-ratelimit-remaining** is 99, which is fine
![image](https://user-images.githubusercontent.com/46223652/90604261-dfbdfd80-e1fc-11ea-930c-eec447fd7a7c.png)

however the next one has only **97** 

![image](https://user-images.githubusercontent.com/46223652/90604389-0da34200-e1fd-11ea-8127-a00c6da16c0d.png)

the one after it 95 and so on

**Comment by hah** [comment]
I've forgot to add that via curl it works fine, so i am not entirely sure what the is the problem

**Comment by TerminalWitchcraft** [comment]
Hi @hah , when you use a browser to make request, the browser automatically sends a request to get a favicon at `/favicon.ico`(I tested on Firefox). Therefore you are seeing this discrepancy. Hope that helps!

**Comment by hah** [comment]
oh lol i am blind, yeah that's it. 

thanks!
