### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by grodin** [TerminalWitchcraft/actix-ratelimit#7]
Now that `actix-web` v3 is available, could I request a new release of `actix-ratelimit` please? I see that the PR #6 was merged but that didn't include a version bump for `actix-ratelimit` and there hasn't been a anything new on crates.io.

If there's anything I can do to help with this, I'm very happy to help out.

Finally, when I request something from an open-source project, I think it's only fair to let them know they are appreciated, so thanks a lot for this project, I certainly would have struggled to implement this myself at this stage in my rust experience!

**Comment by TerminalWitchcraft** [comment]
I'm planning to do the next release with memcached support, however there are some issues related to sharing the memcached connection safely across threads. Once this is done, I will post a release. Any help on this front would be welcomed!

**Comment by robjtede** [comment]
Just checked out the v3 upgrade PR and noticed something that should probably be changed before a new release is made:

```diff
- actix-web = {version = "3.0.1"}
+ actix-web = { version = "3.0.1", default-features = false }
```

...since this lib doesn't require the brotli2 crate (I would assume).

**Comment by grodin** [comment]
> I'm planning to do the next release with memcached support, however there are some issues related to sharing the memcached connection safely across threads. Once this is done, I will post a release. Any help on this front would be welcomed!

Any chance of documenting the issues in a bit more detail? I think it's unlikely I personally have enough skill to get it working, but at least it would  give me or anyone else who wants to have a try a better idea where to start looking. I appreciate the reply in any case!

**Comment by jasonpkovalski** [comment]
Is there a specific reason for waiting to include the `actix-web` version bump with the Memcached support?  I would prefer to avoid forking the repo, if possible.

How far along are you with the issues you mentioned, and are they documented anywhere?  I'm not sure how helpful I'd be, but I could at least try helping out.

**Comment by pikitgb** [comment]
Not sure if related I just upgrade to actix 3 and i had this in my code for a while:
```
App::new()
      .wrap(cors)
      .wrap(
        RateLimiter::new(
        MemoryStoreActor::from(store.clone()).start())
            .with_interval(Duration::from_secs(3))
            .with_max_requests(10))
```

getting this error:

```
error[E0271]: type mismatch resolving `<actix_ratelimit::middleware::RateLimiter<actix_ratelimit::stores::memory::MemoryStoreActor> as actix_service::transform::Transform<<impl actix_service::ServiceFactory as actix_service::ServiceFactory>::Service>>::Response == actix_web::service::ServiceResponse<_>`
   --> src/main.rs:165:8
    |
165 |       .wrap(
    |        ^^^^ expected struct `actix_web::service::ServiceResponse`, found a different struct `actix_web::service::ServiceResponse`
    |
    = note: expected struct `actix_web::service::ServiceResponse<_>` (struct `actix_web::service::ServiceResponse`)
               found struct `actix_web::service::ServiceResponse<_>` (struct `actix_web::service::ServiceResponse`)
    = note: perhaps two different versions of crate `actix_web` are being used?

```

**Comment by tglman** [comment]
Hi,

I did a pull request that smooth out the problem with the lifetime for memcache, now i guess you can progress with the implementation and release the 3.0, I do not know that well memcache to actually be able to do a PR to complete that.

Here is the pr: https://github.com/TerminalWitchcraft/actix-ratelimit/pull/8

Regards

**Comment by tglman** [comment]
Hi, 

Any news on when a release compatible with actix-web 3.0 is going to be out ? do you need any additional help to push this forward ?

Regards

**Comment by TerminalWitchcraft** [comment]
Hi, the memcache version is almost finished. It should be released in few days. Thanks for the PR :)

**Comment by AaronErhardt** [comment]
Looking forward to the next release :)

Btw. I think a rate limiter is something a lot of projects need so it would be great if this crate would officially be part of the actix project.

**Comment by Chaostheorie** [comment]
@TerminalWitchcraft any progress/ help required? If any is required, I would be happy to contribute.
I'm eagerly waiting for the new release to integrate actix-ratelimiter in my project. I would be thankful for an e.g. 0.2.2-alpha release with actix-web bumped but without the memcached feature.

**Comment by TerminalWitchcraft** [comment]
@Chaostheorie I have pushed the working code for memcached in dev branch. Still writing some tests before I release a version. Feel free to look into it if you think you can add any test cases. Regardless, the release should be out in 2-3 days. Apologies for the delay.

**Comment by TerminalWitchcraft** [comment]
I just released a new version on crates.io which supports actix-web v3 and memcached! 

https://crates.io/crates/actix-ratelimit

**Comment by TerminalWitchcraft** [comment]
@AaronErhardt  it depends on what are the goals of actix project in general. Rate-limiting is a very vague topic(it can be implemented on the business logic or endpoint access layer). If the official actix project thinks this ratelimiter aligns with their goals, I'm happy to include it in the official project.

**Comment by robjtede** [comment]
We're happy to accept ownership of well-used community libs under the [actix-exras](https://github.com/actix/actix-extras) repo as was done with `actix-web-httpauth` crate. If you think this would be a good move, @TerminalWitchcraft, let's have a chat on the actix Gitter or Discord.
